# Generated by Django 6.0.2 on 2026-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="название"
                    ),
                ),
                ("weight", models.IntegerField(verbose_name="вес в гр")),
                ("price", models.IntegerField(verbose_name="цена в руб")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Еда"),
                            ("drink", "Напиток"),
                            ("snack", "Снек"),
                        ],
                        max_length=20,
                        verbose_name="категория",
                    ),
                ),
                (
                    "has_allergens",
                    models.BooleanField(
                        default=False, verbose_name="Наличие аллергенов"
                    ),
                ),
            ],
        ),
    ]
